// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// V1beta1ListBranchesResponse Message for response to list branches
//
// swagger:model v1beta1ListBranchesResponse
type V1beta1ListBranchesResponse struct {

	// The list of branches
	Branches []*V1beta1Branch `json:"branches"`

	// A token identifying a page of results the server should return.
	NextPageToken string `json:"nextPageToken,omitempty"`

	// Total number of branches
	TotalSize int64 `json:"totalSize,omitempty"`
}

// Validate validates this v1beta1 list branches response
func (m *V1beta1ListBranchesResponse) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateBranches(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *V1beta1ListBranchesResponse) validateBranches(formats strfmt.Registry) error {
	if swag.IsZero(m.Branches) { // not required
		return nil
	}

	for i := 0; i < len(m.Branches); i++ {
		if swag.IsZero(m.Branches[i]) { // not required
			continue
		}

		if m.Branches[i] != nil {
			if err := m.Branches[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("branches" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("branches" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// ContextValidate validate this v1beta1 list branches response based on the context it is used
func (m *V1beta1ListBranchesResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateBranches(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *V1beta1ListBranchesResponse) contextValidateBranches(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.Branches); i++ {

		if m.Branches[i] != nil {

			if swag.IsZero(m.Branches[i]) { // not required
				return nil
			}

			if err := m.Branches[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("branches" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("branches" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *V1beta1ListBranchesResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *V1beta1ListBranchesResponse) UnmarshalBinary(b []byte) error {
	var res V1beta1ListBranchesResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
