// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// V1ClusterEndpoints Message for the Endpoints for this cluster.
//
// swagger:model v1ClusterEndpoints
type V1ClusterEndpoints struct {

	// Optional . Private Endpoint for this cluster.
	PrivateEndpoint *EndpointsPrivate `json:"privateEndpoint,omitempty"`

	// Optional . Public Endpoint for this cluster.
	PublicEndpoint *EndpointsPublic `json:"publicEndpoint,omitempty"`
}

// Validate validates this v1 cluster endpoints
func (m *V1ClusterEndpoints) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validatePrivateEndpoint(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validatePublicEndpoint(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *V1ClusterEndpoints) validatePrivateEndpoint(formats strfmt.Registry) error {
	if swag.IsZero(m.PrivateEndpoint) { // not required
		return nil
	}

	if m.PrivateEndpoint != nil {
		if err := m.PrivateEndpoint.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("privateEndpoint")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("privateEndpoint")
			}
			return err
		}
	}

	return nil
}

func (m *V1ClusterEndpoints) validatePublicEndpoint(formats strfmt.Registry) error {
	if swag.IsZero(m.PublicEndpoint) { // not required
		return nil
	}

	if m.PublicEndpoint != nil {
		if err := m.PublicEndpoint.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("publicEndpoint")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("publicEndpoint")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this v1 cluster endpoints based on the context it is used
func (m *V1ClusterEndpoints) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidatePrivateEndpoint(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidatePublicEndpoint(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *V1ClusterEndpoints) contextValidatePrivateEndpoint(ctx context.Context, formats strfmt.Registry) error {

	if m.PrivateEndpoint != nil {

		if swag.IsZero(m.PrivateEndpoint) { // not required
			return nil
		}

		if err := m.PrivateEndpoint.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("privateEndpoint")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("privateEndpoint")
			}
			return err
		}
	}

	return nil
}

func (m *V1ClusterEndpoints) contextValidatePublicEndpoint(ctx context.Context, formats strfmt.Registry) error {

	if m.PublicEndpoint != nil {

		if swag.IsZero(m.PublicEndpoint) { // not required
			return nil
		}

		if err := m.PublicEndpoint.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("publicEndpoint")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("publicEndpoint")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *V1ClusterEndpoints) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *V1ClusterEndpoints) UnmarshalBinary(b []byte) error {
	var res V1ClusterEndpoints
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
