/*
TiDB Cloud Serverless Open API

TiDB Cloud Serverless Open API

API version: v1beta1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package imp

import (
	"encoding/json"
	"fmt"
)

// ImportGcsAuthTypeEnum  - SERVICE_ACCOUNT_KEY: The access method is service account key.
type ImportGcsAuthTypeEnum string

// List of ImportGcsAuthType.Enum
const (
	IMPORTGCSAUTHTYPEENUM_SERVICE_ACCOUNT_KEY ImportGcsAuthTypeEnum = "SERVICE_ACCOUNT_KEY"
)

// All allowed values of ImportGcsAuthTypeEnum enum
var AllowedImportGcsAuthTypeEnumEnumValues = []ImportGcsAuthTypeEnum{
	"SERVICE_ACCOUNT_KEY",
}

func (v *ImportGcsAuthTypeEnum) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := ImportGcsAuthTypeEnum(value)
	for _, existing := range AllowedImportGcsAuthTypeEnumEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid ImportGcsAuthTypeEnum", value)
}

// NewImportGcsAuthTypeEnumFromValue returns a pointer to a valid ImportGcsAuthTypeEnum
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewImportGcsAuthTypeEnumFromValue(v string) (*ImportGcsAuthTypeEnum, error) {
	ev := ImportGcsAuthTypeEnum(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for ImportGcsAuthTypeEnum: valid values are %v", v, AllowedImportGcsAuthTypeEnumEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v ImportGcsAuthTypeEnum) IsValid() bool {
	for _, existing := range AllowedImportGcsAuthTypeEnumEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to ImportGcsAuthType.Enum value
func (v ImportGcsAuthTypeEnum) Ptr() *ImportGcsAuthTypeEnum {
	return &v
}

type NullableImportGcsAuthTypeEnum struct {
	value *ImportGcsAuthTypeEnum
	isSet bool
}

func (v NullableImportGcsAuthTypeEnum) Get() *ImportGcsAuthTypeEnum {
	return v.value
}

func (v *NullableImportGcsAuthTypeEnum) Set(val *ImportGcsAuthTypeEnum) {
	v.value = val
	v.isSet = true
}

func (v NullableImportGcsAuthTypeEnum) IsSet() bool {
	return v.isSet
}

func (v *NullableImportGcsAuthTypeEnum) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableImportGcsAuthTypeEnum(val *ImportGcsAuthTypeEnum) *NullableImportGcsAuthTypeEnum {
	return &NullableImportGcsAuthTypeEnum{value: val, isSet: true}
}

func (v NullableImportGcsAuthTypeEnum) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableImportGcsAuthTypeEnum) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
