header:
  license:
    spdx-id: Apache-2.0
    copyright-owner: PingCAP, Inc.
  paths:
    - '**/*.sh'
    - '**/*.go'
  paths-ignore:
    - '**/mock/**'
    - 'pkg/tidbcloud/import/**'
  comment: on-failure
