// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/validate"
)

// Serverlessv1beta1ClusterView Enum for the different types of detail view to be returned for a TiDB Serverless cluster.
//
//   - CLUSTER_VIEW_UNSPECIFIED: The server default is used if unspecified.
//   - BASIC: Only basic information about the cluster is returned.
//   - FULL: All details about the cluster are returned.
//
// swagger:model serverlessv1beta1ClusterView
type Serverlessv1beta1ClusterView string

func NewServerlessv1beta1ClusterView(value Serverlessv1beta1ClusterView) *Serverlessv1beta1ClusterView {
	return &value
}

// Pointer returns a pointer to a freshly-allocated Serverlessv1beta1ClusterView.
func (m Serverlessv1beta1ClusterView) Pointer() *Serverlessv1beta1ClusterView {
	return &m
}

const (

	// Serverlessv1beta1ClusterViewCLUSTERVIEWUNSPECIFIED captures enum value "CLUSTER_VIEW_UNSPECIFIED"
	Serverlessv1beta1ClusterViewCLUSTERVIEWUNSPECIFIED Serverlessv1beta1ClusterView = "CLUSTER_VIEW_UNSPECIFIED"

	// Serverlessv1beta1ClusterViewBASIC captures enum value "BASIC"
	Serverlessv1beta1ClusterViewBASIC Serverlessv1beta1ClusterView = "BASIC"

	// Serverlessv1beta1ClusterViewFULL captures enum value "FULL"
	Serverlessv1beta1ClusterViewFULL Serverlessv1beta1ClusterView = "FULL"
)

// for schema
var serverlessv1beta1ClusterViewEnum []interface{}

func init() {
	var res []Serverlessv1beta1ClusterView
	if err := json.Unmarshal([]byte(`["CLUSTER_VIEW_UNSPECIFIED","BASIC","FULL"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		serverlessv1beta1ClusterViewEnum = append(serverlessv1beta1ClusterViewEnum, v)
	}
}

func (m Serverlessv1beta1ClusterView) validateServerlessv1beta1ClusterViewEnum(path, location string, value Serverlessv1beta1ClusterView) error {
	if err := validate.EnumCase(path, location, value, serverlessv1beta1ClusterViewEnum, true); err != nil {
		return err
	}
	return nil
}

// Validate validates this serverlessv1beta1 cluster view
func (m Serverlessv1beta1ClusterView) Validate(formats strfmt.Registry) error {
	var res []error

	// value enum
	if err := m.validateServerlessv1beta1ClusterViewEnum("", "body", m); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// ContextValidate validates this serverlessv1beta1 cluster view based on context it is used
func (m Serverlessv1beta1ClusterView) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}
