run:
  timeout: 10m
linters:
  disable-all: true
  enable:
    - asciicheck
    - bodyclose
    - durationcheck
    - errcheck
    - goimports
    - gosec
    - gosimple
    - ineffassign
    - makezero
    - prealloc
    - predeclared
    - rowserrcheck
    - staticcheck
    - stylecheck
    - typecheck
    - unused

linters-settings:
  staticcheck:
    checks: ["S1002","S1004","S1007","S1009","S1010","S1012","S1019","S1020","S1021","S1024","S1030","SA2*","SA3*","SA4009","SA5*","SA6000","SA6001","SA6005", "-SA2002"]
  stylecheck:
    checks: ["-ST1003"]
  gosec:
    severity: "low"
    confidence: "low"
    excludes:
      - G101
      - G115
      - G404
      # exclude warnings of using crypto/sha1
      - G505

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - gosec
        - rowserrcheck
        - makezero
