project_name: ticloud

before:
  hooks:
    - go mod tidy
builds:
  - <<: &build_defaults
      main: ./cmd/ticloud/main.go
      ldflags:
        - -s -w -X main.version={{.Version}} -X main.commit={{.ShortCommit}} -X main.date={{.Date}}
      flags:
        - -trimpath
      binary: "ticloud"
    env:
      - CGO_ENABLED=0
    id: linux
    goos: [linux]
    goarch: [amd64,arm64]
  - <<: *build_defaults
    id: macos
    goos: [darwin]
    goarch: [amd64,arm64]
  - <<: *build_defaults
    id: windows
    goos: [windows]
    goarch: [amd64]

archives:
  - id: nix
    builds: [linux, macos]
    <<: &archive_defaults
      name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
      wrap_in_directory: false
    format: tar.gz
  - id: windows
    builds: [windows]
    <<: *archive_defaults
    format: zip

nfpms:
  - maintainer: PingCAP Inc.
    description: The TiDB Cloud CLI
    homepage: https://tidbcloud.com/
    license: Apache 2.0
    builds: [ linux ]
    formats: [ deb,rpm ]

checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"

