// Code generated by go-swagger; DO NOT EDIT.

package export_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewExportServiceGetExportParams creates a new ExportServiceGetExportParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewExportServiceGetExportParams() *ExportServiceGetExportParams {
	return &ExportServiceGetExportParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewExportServiceGetExportParamsWithTimeout creates a new ExportServiceGetExportParams object
// with the ability to set a timeout on a request.
func NewExportServiceGetExportParamsWithTimeout(timeout time.Duration) *ExportServiceGetExportParams {
	return &ExportServiceGetExportParams{
		timeout: timeout,
	}
}

// NewExportServiceGetExportParamsWithContext creates a new ExportServiceGetExportParams object
// with the ability to set a context for a request.
func NewExportServiceGetExportParamsWithContext(ctx context.Context) *ExportServiceGetExportParams {
	return &ExportServiceGetExportParams{
		Context: ctx,
	}
}

// NewExportServiceGetExportParamsWithHTTPClient creates a new ExportServiceGetExportParams object
// with the ability to set a custom HTTPClient for a request.
func NewExportServiceGetExportParamsWithHTTPClient(client *http.Client) *ExportServiceGetExportParams {
	return &ExportServiceGetExportParams{
		HTTPClient: client,
	}
}

/*
ExportServiceGetExportParams contains all the parameters to send to the API endpoint

	for the export service get export operation.

	Typically these are written to a http.Request.
*/
type ExportServiceGetExportParams struct {

	/* ClusterID.

	   Required. The ID of the cluster.
	*/
	ClusterID string

	/* ExportID.

	   Required. The ID of the export to be retrieved.
	*/
	ExportID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the export service get export params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ExportServiceGetExportParams) WithDefaults() *ExportServiceGetExportParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the export service get export params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ExportServiceGetExportParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the export service get export params
func (o *ExportServiceGetExportParams) WithTimeout(timeout time.Duration) *ExportServiceGetExportParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the export service get export params
func (o *ExportServiceGetExportParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the export service get export params
func (o *ExportServiceGetExportParams) WithContext(ctx context.Context) *ExportServiceGetExportParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the export service get export params
func (o *ExportServiceGetExportParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the export service get export params
func (o *ExportServiceGetExportParams) WithHTTPClient(client *http.Client) *ExportServiceGetExportParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the export service get export params
func (o *ExportServiceGetExportParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithClusterID adds the clusterID to the export service get export params
func (o *ExportServiceGetExportParams) WithClusterID(clusterID string) *ExportServiceGetExportParams {
	o.SetClusterID(clusterID)
	return o
}

// SetClusterID adds the clusterId to the export service get export params
func (o *ExportServiceGetExportParams) SetClusterID(clusterID string) {
	o.ClusterID = clusterID
}

// WithExportID adds the exportID to the export service get export params
func (o *ExportServiceGetExportParams) WithExportID(exportID string) *ExportServiceGetExportParams {
	o.SetExportID(exportID)
	return o
}

// SetExportID adds the exportId to the export service get export params
func (o *ExportServiceGetExportParams) SetExportID(exportID string) {
	o.ExportID = exportID
}

// WriteToRequest writes these params to a swagger request
func (o *ExportServiceGetExportParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param clusterId
	if err := r.SetPathParam("clusterId", o.ClusterID); err != nil {
		return err
	}

	// path param exportId
	if err := r.SetPathParam("exportId", o.ExportID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
