/*
TiDB Cloud Serverless Open API

TiDB Cloud Serverless Open API

API version: v1beta1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package branch

import (
	"encoding/json"
	"fmt"
)

// BranchServiceGetBranchViewParameter the model 'BranchServiceGetBranchViewParameter'
type BranchServiceGetBranchViewParameter string

// List of BranchService_GetBranch_view_parameter
const (
	BRANCHSERVICEGETBRANCHVIEWPARAMETER_BASIC BranchServiceGetBranchViewParameter = "BASIC"
	BRANCHSERVICEGETBRANCHVIEWPARAMETER_FULL  BranchServiceGetBranchViewParameter = "FULL"
)

// All allowed values of BranchServiceGetBranchViewParameter enum
var AllowedBranchServiceGetBranchViewParameterEnumValues = []BranchServiceGetBranchViewParameter{
	"BASIC",
	"FULL",
}

func (v *BranchServiceGetBranchViewParameter) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := BranchServiceGetBranchViewParameter(value)
	for _, existing := range AllowedBranchServiceGetBranchViewParameterEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid BranchServiceGetBranchViewParameter", value)
}

// NewBranchServiceGetBranchViewParameterFromValue returns a pointer to a valid BranchServiceGetBranchViewParameter
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewBranchServiceGetBranchViewParameterFromValue(v string) (*BranchServiceGetBranchViewParameter, error) {
	ev := BranchServiceGetBranchViewParameter(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for BranchServiceGetBranchViewParameter: valid values are %v", v, AllowedBranchServiceGetBranchViewParameterEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v BranchServiceGetBranchViewParameter) IsValid() bool {
	for _, existing := range AllowedBranchServiceGetBranchViewParameterEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to BranchService_GetBranch_view_parameter value
func (v BranchServiceGetBranchViewParameter) Ptr() *BranchServiceGetBranchViewParameter {
	return &v
}

type NullableBranchServiceGetBranchViewParameter struct {
	value *BranchServiceGetBranchViewParameter
	isSet bool
}

func (v NullableBranchServiceGetBranchViewParameter) Get() *BranchServiceGetBranchViewParameter {
	return v.value
}

func (v *NullableBranchServiceGetBranchViewParameter) Set(val *BranchServiceGetBranchViewParameter) {
	v.value = val
	v.isSet = true
}

func (v NullableBranchServiceGetBranchViewParameter) IsSet() bool {
	return v.isSet
}

func (v *NullableBranchServiceGetBranchViewParameter) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBranchServiceGetBranchViewParameter(val *BranchServiceGetBranchViewParameter) *NullableBranchServiceGetBranchViewParameter {
	return &NullableBranchServiceGetBranchViewParameter{value: val, isSet: true}
}

func (v NullableBranchServiceGetBranchViewParameter) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBranchServiceGetBranchViewParameter) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
