/*
TiDB Cloud Starter and Essential Open API

TiDB Cloud Starter and Essential Open API

API version: v1beta1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package dm

import (
	"encoding/json"
)

// checks if the DMServiceOperateTaskBody type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DMServiceOperateTaskBody{}

// DMServiceOperateTaskBody struct for DMServiceOperateTaskBody
type DMServiceOperateTaskBody struct {
	Op                   *OperateDMTaskReqOperation `json:"op,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _DMServiceOperateTaskBody DMServiceOperateTaskBody

// NewDMServiceOperateTaskBody instantiates a new DMServiceOperateTaskBody object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDMServiceOperateTaskBody() *DMServiceOperateTaskBody {
	this := DMServiceOperateTaskBody{}
	return &this
}

// NewDMServiceOperateTaskBodyWithDefaults instantiates a new DMServiceOperateTaskBody object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDMServiceOperateTaskBodyWithDefaults() *DMServiceOperateTaskBody {
	this := DMServiceOperateTaskBody{}
	return &this
}

// GetOp returns the Op field value if set, zero value otherwise.
func (o *DMServiceOperateTaskBody) GetOp() OperateDMTaskReqOperation {
	if o == nil || IsNil(o.Op) {
		var ret OperateDMTaskReqOperation
		return ret
	}
	return *o.Op
}

// GetOpOk returns a tuple with the Op field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DMServiceOperateTaskBody) GetOpOk() (*OperateDMTaskReqOperation, bool) {
	if o == nil || IsNil(o.Op) {
		return nil, false
	}
	return o.Op, true
}

// HasOp returns a boolean if a field has been set.
func (o *DMServiceOperateTaskBody) HasOp() bool {
	if o != nil && !IsNil(o.Op) {
		return true
	}

	return false
}

// SetOp gets a reference to the given OperateDMTaskReqOperation and assigns it to the Op field.
func (o *DMServiceOperateTaskBody) SetOp(v OperateDMTaskReqOperation) {
	o.Op = &v
}

func (o DMServiceOperateTaskBody) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DMServiceOperateTaskBody) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Op) {
		toSerialize["op"] = o.Op
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *DMServiceOperateTaskBody) UnmarshalJSON(data []byte) (err error) {
	varDMServiceOperateTaskBody := _DMServiceOperateTaskBody{}

	err = json.Unmarshal(data, &varDMServiceOperateTaskBody)

	if err != nil {
		return err
	}

	*o = DMServiceOperateTaskBody(varDMServiceOperateTaskBody)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "op")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableDMServiceOperateTaskBody struct {
	value *DMServiceOperateTaskBody
	isSet bool
}

func (v NullableDMServiceOperateTaskBody) Get() *DMServiceOperateTaskBody {
	return v.value
}

func (v *NullableDMServiceOperateTaskBody) Set(val *DMServiceOperateTaskBody) {
	v.value = val
	v.isSet = true
}

func (v NullableDMServiceOperateTaskBody) IsSet() bool {
	return v.isSet
}

func (v *NullableDMServiceOperateTaskBody) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDMServiceOperateTaskBody(val *DMServiceOperateTaskBody) *NullableDMServiceOperateTaskBody {
	return &NullableDMServiceOperateTaskBody{value: val, isSet: true}
}

func (v NullableDMServiceOperateTaskBody) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDMServiceOperateTaskBody) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
