// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// OpenapiCreateImportReq openapi create import req
//
// swagger:model openapiCreateImportReq
type OpenapiCreateImportReq struct {

	// The arn of AWS IAM role.
	// Required: true
	AwsRoleArn *string `json:"aws_role_arn"`

	// The ID of the cluster.
	// Example: 1
	// Required: true
	ClusterID *string `json:"cluster_id"`

	// The CSV configuration.
	CsvFormat *OpenapiCustomCSVFormat `json:"csv_format,omitempty"`

	// The format of data to import.
	// Required: true
	DataFormat *OpenapiDataFormat `json:"data_format"`

	// The ID of the project.
	// Example: 1
	// Required: true
	ProjectID *string `json:"project_id"`

	// The full s3 path that contains data to import.
	// Required: true
	SourceURL *string `json:"source_url"`
}

// Validate validates this openapi create import req
func (m *OpenapiCreateImportReq) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateAwsRoleArn(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateClusterID(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateCsvFormat(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateDataFormat(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateProjectID(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateSourceURL(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *OpenapiCreateImportReq) validateAwsRoleArn(formats strfmt.Registry) error {

	if err := validate.Required("aws_role_arn", "body", m.AwsRoleArn); err != nil {
		return err
	}

	return nil
}

func (m *OpenapiCreateImportReq) validateClusterID(formats strfmt.Registry) error {

	if err := validate.Required("cluster_id", "body", m.ClusterID); err != nil {
		return err
	}

	return nil
}

func (m *OpenapiCreateImportReq) validateCsvFormat(formats strfmt.Registry) error {
	if swag.IsZero(m.CsvFormat) { // not required
		return nil
	}

	if m.CsvFormat != nil {
		if err := m.CsvFormat.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("csv_format")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("csv_format")
			}
			return err
		}
	}

	return nil
}

func (m *OpenapiCreateImportReq) validateDataFormat(formats strfmt.Registry) error {

	if err := validate.Required("data_format", "body", m.DataFormat); err != nil {
		return err
	}

	if err := validate.Required("data_format", "body", m.DataFormat); err != nil {
		return err
	}

	if m.DataFormat != nil {
		if err := m.DataFormat.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("data_format")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("data_format")
			}
			return err
		}
	}

	return nil
}

func (m *OpenapiCreateImportReq) validateProjectID(formats strfmt.Registry) error {

	if err := validate.Required("project_id", "body", m.ProjectID); err != nil {
		return err
	}

	return nil
}

func (m *OpenapiCreateImportReq) validateSourceURL(formats strfmt.Registry) error {

	if err := validate.Required("source_url", "body", m.SourceURL); err != nil {
		return err
	}

	return nil
}

// ContextValidate validate this openapi create import req based on the context it is used
func (m *OpenapiCreateImportReq) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateCsvFormat(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateDataFormat(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *OpenapiCreateImportReq) contextValidateCsvFormat(ctx context.Context, formats strfmt.Registry) error {

	if m.CsvFormat != nil {
		if err := m.CsvFormat.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("csv_format")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("csv_format")
			}
			return err
		}
	}

	return nil
}

func (m *OpenapiCreateImportReq) contextValidateDataFormat(ctx context.Context, formats strfmt.Registry) error {

	if m.DataFormat != nil {
		if err := m.DataFormat.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("data_format")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("data_format")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *OpenapiCreateImportReq) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *OpenapiCreateImportReq) UnmarshalBinary(b []byte) error {
	var res OpenapiCreateImportReq
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
