/*
TiDB Cloud Starter and Essential Database Audit Logging Open API

TiDB Cloud Starter and Essential Database Audit Logging Open API

API version: v1beta1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package auditlog

import (
	"encoding/json"
)

// checks if the ListAuditLogFilterRulesResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ListAuditLogFilterRulesResponse{}

// ListAuditLogFilterRulesResponse struct for ListAuditLogFilterRulesResponse
type ListAuditLogFilterRulesResponse struct {
	FilterRules          []AuditLogFilterRule `json:"filterRules,omitempty"`
	NextPageToken        *string              `json:"nextPageToken,omitempty"`
	TotalSize            *int64               `json:"totalSize,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _ListAuditLogFilterRulesResponse ListAuditLogFilterRulesResponse

// NewListAuditLogFilterRulesResponse instantiates a new ListAuditLogFilterRulesResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewListAuditLogFilterRulesResponse() *ListAuditLogFilterRulesResponse {
	this := ListAuditLogFilterRulesResponse{}
	return &this
}

// NewListAuditLogFilterRulesResponseWithDefaults instantiates a new ListAuditLogFilterRulesResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewListAuditLogFilterRulesResponseWithDefaults() *ListAuditLogFilterRulesResponse {
	this := ListAuditLogFilterRulesResponse{}
	return &this
}

// GetFilterRules returns the FilterRules field value if set, zero value otherwise.
func (o *ListAuditLogFilterRulesResponse) GetFilterRules() []AuditLogFilterRule {
	if o == nil || IsNil(o.FilterRules) {
		var ret []AuditLogFilterRule
		return ret
	}
	return o.FilterRules
}

// GetFilterRulesOk returns a tuple with the FilterRules field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListAuditLogFilterRulesResponse) GetFilterRulesOk() ([]AuditLogFilterRule, bool) {
	if o == nil || IsNil(o.FilterRules) {
		return nil, false
	}
	return o.FilterRules, true
}

// HasFilterRules returns a boolean if a field has been set.
func (o *ListAuditLogFilterRulesResponse) HasFilterRules() bool {
	if o != nil && !IsNil(o.FilterRules) {
		return true
	}

	return false
}

// SetFilterRules gets a reference to the given []AuditLogFilterRule and assigns it to the FilterRules field.
func (o *ListAuditLogFilterRulesResponse) SetFilterRules(v []AuditLogFilterRule) {
	o.FilterRules = v
}

// GetNextPageToken returns the NextPageToken field value if set, zero value otherwise.
func (o *ListAuditLogFilterRulesResponse) GetNextPageToken() string {
	if o == nil || IsNil(o.NextPageToken) {
		var ret string
		return ret
	}
	return *o.NextPageToken
}

// GetNextPageTokenOk returns a tuple with the NextPageToken field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListAuditLogFilterRulesResponse) GetNextPageTokenOk() (*string, bool) {
	if o == nil || IsNil(o.NextPageToken) {
		return nil, false
	}
	return o.NextPageToken, true
}

// HasNextPageToken returns a boolean if a field has been set.
func (o *ListAuditLogFilterRulesResponse) HasNextPageToken() bool {
	if o != nil && !IsNil(o.NextPageToken) {
		return true
	}

	return false
}

// SetNextPageToken gets a reference to the given string and assigns it to the NextPageToken field.
func (o *ListAuditLogFilterRulesResponse) SetNextPageToken(v string) {
	o.NextPageToken = &v
}

// GetTotalSize returns the TotalSize field value if set, zero value otherwise.
func (o *ListAuditLogFilterRulesResponse) GetTotalSize() int64 {
	if o == nil || IsNil(o.TotalSize) {
		var ret int64
		return ret
	}
	return *o.TotalSize
}

// GetTotalSizeOk returns a tuple with the TotalSize field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListAuditLogFilterRulesResponse) GetTotalSizeOk() (*int64, bool) {
	if o == nil || IsNil(o.TotalSize) {
		return nil, false
	}
	return o.TotalSize, true
}

// HasTotalSize returns a boolean if a field has been set.
func (o *ListAuditLogFilterRulesResponse) HasTotalSize() bool {
	if o != nil && !IsNil(o.TotalSize) {
		return true
	}

	return false
}

// SetTotalSize gets a reference to the given int64 and assigns it to the TotalSize field.
func (o *ListAuditLogFilterRulesResponse) SetTotalSize(v int64) {
	o.TotalSize = &v
}

func (o ListAuditLogFilterRulesResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ListAuditLogFilterRulesResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.FilterRules) {
		toSerialize["filterRules"] = o.FilterRules
	}
	if !IsNil(o.NextPageToken) {
		toSerialize["nextPageToken"] = o.NextPageToken
	}
	if !IsNil(o.TotalSize) {
		toSerialize["totalSize"] = o.TotalSize
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ListAuditLogFilterRulesResponse) UnmarshalJSON(data []byte) (err error) {
	varListAuditLogFilterRulesResponse := _ListAuditLogFilterRulesResponse{}

	err = json.Unmarshal(data, &varListAuditLogFilterRulesResponse)

	if err != nil {
		return err
	}

	*o = ListAuditLogFilterRulesResponse(varListAuditLogFilterRulesResponse)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "filterRules")
		delete(additionalProperties, "nextPageToken")
		delete(additionalProperties, "totalSize")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableListAuditLogFilterRulesResponse struct {
	value *ListAuditLogFilterRulesResponse
	isSet bool
}

func (v NullableListAuditLogFilterRulesResponse) Get() *ListAuditLogFilterRulesResponse {
	return v.value
}

func (v *NullableListAuditLogFilterRulesResponse) Set(val *ListAuditLogFilterRulesResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableListAuditLogFilterRulesResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableListAuditLogFilterRulesResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListAuditLogFilterRulesResponse(val *ListAuditLogFilterRulesResponse) *NullableListAuditLogFilterRulesResponse {
	return &NullableListAuditLogFilterRulesResponse{value: val, isSet: true}
}

func (v NullableListAuditLogFilterRulesResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListAuditLogFilterRulesResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
