/*
TiDB Cloud Serverless CDC Open API

TiDB Cloud Serverless CDC Open API

API version: v1beta1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package cdc

import (
	"encoding/json"
	"time"
)

// checks if the StartPosition type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &StartPosition{}

// StartPosition struct for StartPosition
type StartPosition struct {
	Mode                 *StartModeEnum `json:"mode,omitempty"`
	Tso                  *string        `json:"tso,omitempty"`
	Time                 *time.Time     `json:"time,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _StartPosition StartPosition

// NewStartPosition instantiates a new StartPosition object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewStartPosition() *StartPosition {
	this := StartPosition{}
	return &this
}

// NewStartPositionWithDefaults instantiates a new StartPosition object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewStartPositionWithDefaults() *StartPosition {
	this := StartPosition{}
	return &this
}

// GetMode returns the Mode field value if set, zero value otherwise.
func (o *StartPosition) GetMode() StartModeEnum {
	if o == nil || IsNil(o.Mode) {
		var ret StartModeEnum
		return ret
	}
	return *o.Mode
}

// GetModeOk returns a tuple with the Mode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StartPosition) GetModeOk() (*StartModeEnum, bool) {
	if o == nil || IsNil(o.Mode) {
		return nil, false
	}
	return o.Mode, true
}

// HasMode returns a boolean if a field has been set.
func (o *StartPosition) HasMode() bool {
	if o != nil && !IsNil(o.Mode) {
		return true
	}

	return false
}

// SetMode gets a reference to the given StartModeEnum and assigns it to the Mode field.
func (o *StartPosition) SetMode(v StartModeEnum) {
	o.Mode = &v
}

// GetTso returns the Tso field value if set, zero value otherwise.
func (o *StartPosition) GetTso() string {
	if o == nil || IsNil(o.Tso) {
		var ret string
		return ret
	}
	return *o.Tso
}

// GetTsoOk returns a tuple with the Tso field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StartPosition) GetTsoOk() (*string, bool) {
	if o == nil || IsNil(o.Tso) {
		return nil, false
	}
	return o.Tso, true
}

// HasTso returns a boolean if a field has been set.
func (o *StartPosition) HasTso() bool {
	if o != nil && !IsNil(o.Tso) {
		return true
	}

	return false
}

// SetTso gets a reference to the given string and assigns it to the Tso field.
func (o *StartPosition) SetTso(v string) {
	o.Tso = &v
}

// GetTime returns the Time field value if set, zero value otherwise.
func (o *StartPosition) GetTime() time.Time {
	if o == nil || IsNil(o.Time) {
		var ret time.Time
		return ret
	}
	return *o.Time
}

// GetTimeOk returns a tuple with the Time field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StartPosition) GetTimeOk() (*time.Time, bool) {
	if o == nil || IsNil(o.Time) {
		return nil, false
	}
	return o.Time, true
}

// HasTime returns a boolean if a field has been set.
func (o *StartPosition) HasTime() bool {
	if o != nil && !IsNil(o.Time) {
		return true
	}

	return false
}

// SetTime gets a reference to the given time.Time and assigns it to the Time field.
func (o *StartPosition) SetTime(v time.Time) {
	o.Time = &v
}

func (o StartPosition) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o StartPosition) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Mode) {
		toSerialize["mode"] = o.Mode
	}
	if !IsNil(o.Tso) {
		toSerialize["tso"] = o.Tso
	}
	if !IsNil(o.Time) {
		toSerialize["time"] = o.Time
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *StartPosition) UnmarshalJSON(data []byte) (err error) {
	varStartPosition := _StartPosition{}

	err = json.Unmarshal(data, &varStartPosition)

	if err != nil {
		return err
	}

	*o = StartPosition(varStartPosition)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "mode")
		delete(additionalProperties, "tso")
		delete(additionalProperties, "time")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableStartPosition struct {
	value *StartPosition
	isSet bool
}

func (v NullableStartPosition) Get() *StartPosition {
	return v.value
}

func (v *NullableStartPosition) Set(val *StartPosition) {
	v.value = val
	v.isSet = true
}

func (v NullableStartPosition) IsSet() bool {
	return v.isSet
}

func (v *NullableStartPosition) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableStartPosition(val *StartPosition) *NullableStartPosition {
	return &NullableStartPosition{value: val, isSet: true}
}

func (v NullableStartPosition) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableStartPosition) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
