// Code generated by go-swagger; DO NOT EDIT.

package import_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"tidbcloud-cli/pkg/tidbcloud/import/models"
)

// ListImportsReader is a Reader for the ListImports structure.
type ListImportsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ListImportsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewListImportsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewListImportsDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewListImportsOK creates a ListImportsOK with default headers values
func NewListImportsOK() *ListImportsOK {
	return &ListImportsOK{}
}

/*
ListImportsOK describes a response with status code 200, with default header values.

A successful response.
*/
type ListImportsOK struct {
	Payload *models.OpenapiListImportsResp
}

// IsSuccess returns true when this list imports o k response has a 2xx status code
func (o *ListImportsOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this list imports o k response has a 3xx status code
func (o *ListImportsOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this list imports o k response has a 4xx status code
func (o *ListImportsOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this list imports o k response has a 5xx status code
func (o *ListImportsOK) IsServerError() bool {
	return false
}

// IsCode returns true when this list imports o k response a status code equal to that given
func (o *ListImportsOK) IsCode(code int) bool {
	return code == 200
}

func (o *ListImportsOK) Error() string {
	return fmt.Sprintf("[GET /api/internal/projects/{project_id}/clusters/{cluster_id}/imports][%d] listImportsOK  %+v", 200, o.Payload)
}

func (o *ListImportsOK) String() string {
	return fmt.Sprintf("[GET /api/internal/projects/{project_id}/clusters/{cluster_id}/imports][%d] listImportsOK  %+v", 200, o.Payload)
}

func (o *ListImportsOK) GetPayload() *models.OpenapiListImportsResp {
	return o.Payload
}

func (o *ListImportsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.OpenapiListImportsResp)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewListImportsDefault creates a ListImportsDefault with default headers values
func NewListImportsDefault(code int) *ListImportsDefault {
	return &ListImportsDefault{
		_statusCode: code,
	}
}

/*
ListImportsDefault describes a response with status code -1, with default header values.

An unexpected error response.
*/
type ListImportsDefault struct {
	_statusCode int

	Payload *models.GooglerpcStatus
}

// Code gets the status code for the list imports default response
func (o *ListImportsDefault) Code() int {
	return o._statusCode
}

// IsSuccess returns true when this list imports default response has a 2xx status code
func (o *ListImportsDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this list imports default response has a 3xx status code
func (o *ListImportsDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this list imports default response has a 4xx status code
func (o *ListImportsDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this list imports default response has a 5xx status code
func (o *ListImportsDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this list imports default response a status code equal to that given
func (o *ListImportsDefault) IsCode(code int) bool {
	return o._statusCode == code
}

func (o *ListImportsDefault) Error() string {
	return fmt.Sprintf("[GET /api/internal/projects/{project_id}/clusters/{cluster_id}/imports][%d] ListImports default  %+v", o._statusCode, o.Payload)
}

func (o *ListImportsDefault) String() string {
	return fmt.Sprintf("[GET /api/internal/projects/{project_id}/clusters/{cluster_id}/imports][%d] ListImports default  %+v", o._statusCode, o.Payload)
}

func (o *ListImportsDefault) GetPayload() *models.GooglerpcStatus {
	return o.Payload
}

func (o *ListImportsDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GooglerpcStatus)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
