// Code generated by go-swagger; DO NOT EDIT.

package import_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewImportServiceCancelMultipartUploadParams creates a new ImportServiceCancelMultipartUploadParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewImportServiceCancelMultipartUploadParams() *ImportServiceCancelMultipartUploadParams {
	return &ImportServiceCancelMultipartUploadParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewImportServiceCancelMultipartUploadParamsWithTimeout creates a new ImportServiceCancelMultipartUploadParams object
// with the ability to set a timeout on a request.
func NewImportServiceCancelMultipartUploadParamsWithTimeout(timeout time.Duration) *ImportServiceCancelMultipartUploadParams {
	return &ImportServiceCancelMultipartUploadParams{
		timeout: timeout,
	}
}

// NewImportServiceCancelMultipartUploadParamsWithContext creates a new ImportServiceCancelMultipartUploadParams object
// with the ability to set a context for a request.
func NewImportServiceCancelMultipartUploadParamsWithContext(ctx context.Context) *ImportServiceCancelMultipartUploadParams {
	return &ImportServiceCancelMultipartUploadParams{
		Context: ctx,
	}
}

// NewImportServiceCancelMultipartUploadParamsWithHTTPClient creates a new ImportServiceCancelMultipartUploadParams object
// with the ability to set a custom HTTPClient for a request.
func NewImportServiceCancelMultipartUploadParamsWithHTTPClient(client *http.Client) *ImportServiceCancelMultipartUploadParams {
	return &ImportServiceCancelMultipartUploadParams{
		HTTPClient: client,
	}
}

/*
ImportServiceCancelMultipartUploadParams contains all the parameters to send to the API endpoint

	for the import service cancel multipart upload operation.

	Typically these are written to a http.Request.
*/
type ImportServiceCancelMultipartUploadParams struct {

	/* ClusterID.

	   The ID of the cluster to import into
	*/
	ClusterID string

	/* FileName.

	   The name of the file to import
	*/
	FileName string

	/* UploadID.

	   The ID of the upload
	*/
	UploadID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the import service cancel multipart upload params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ImportServiceCancelMultipartUploadParams) WithDefaults() *ImportServiceCancelMultipartUploadParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the import service cancel multipart upload params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ImportServiceCancelMultipartUploadParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the import service cancel multipart upload params
func (o *ImportServiceCancelMultipartUploadParams) WithTimeout(timeout time.Duration) *ImportServiceCancelMultipartUploadParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the import service cancel multipart upload params
func (o *ImportServiceCancelMultipartUploadParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the import service cancel multipart upload params
func (o *ImportServiceCancelMultipartUploadParams) WithContext(ctx context.Context) *ImportServiceCancelMultipartUploadParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the import service cancel multipart upload params
func (o *ImportServiceCancelMultipartUploadParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the import service cancel multipart upload params
func (o *ImportServiceCancelMultipartUploadParams) WithHTTPClient(client *http.Client) *ImportServiceCancelMultipartUploadParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the import service cancel multipart upload params
func (o *ImportServiceCancelMultipartUploadParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithClusterID adds the clusterID to the import service cancel multipart upload params
func (o *ImportServiceCancelMultipartUploadParams) WithClusterID(clusterID string) *ImportServiceCancelMultipartUploadParams {
	o.SetClusterID(clusterID)
	return o
}

// SetClusterID adds the clusterId to the import service cancel multipart upload params
func (o *ImportServiceCancelMultipartUploadParams) SetClusterID(clusterID string) {
	o.ClusterID = clusterID
}

// WithFileName adds the fileName to the import service cancel multipart upload params
func (o *ImportServiceCancelMultipartUploadParams) WithFileName(fileName string) *ImportServiceCancelMultipartUploadParams {
	o.SetFileName(fileName)
	return o
}

// SetFileName adds the fileName to the import service cancel multipart upload params
func (o *ImportServiceCancelMultipartUploadParams) SetFileName(fileName string) {
	o.FileName = fileName
}

// WithUploadID adds the uploadID to the import service cancel multipart upload params
func (o *ImportServiceCancelMultipartUploadParams) WithUploadID(uploadID string) *ImportServiceCancelMultipartUploadParams {
	o.SetUploadID(uploadID)
	return o
}

// SetUploadID adds the uploadId to the import service cancel multipart upload params
func (o *ImportServiceCancelMultipartUploadParams) SetUploadID(uploadID string) {
	o.UploadID = uploadID
}

// WriteToRequest writes these params to a swagger request
func (o *ImportServiceCancelMultipartUploadParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param clusterId
	if err := r.SetPathParam("clusterId", o.ClusterID); err != nil {
		return err
	}

	// query param fileName
	qrFileName := o.FileName
	qFileName := qrFileName
	if qFileName != "" {

		if err := r.SetQueryParam("fileName", qFileName); err != nil {
			return err
		}
	}

	// query param uploadId
	qrUploadID := o.UploadID
	qUploadID := qrUploadID
	if qUploadID != "" {

		if err := r.SetQueryParam("uploadId", qUploadID); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
