/*
TiDB Cloud Starter and Essential API

TiDB Cloud Starter and Essential API

API version: v1beta1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package migration

import (
	"encoding/json"
	"fmt"
)

// checks if the MigrationServiceCreateMigrationBody type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MigrationServiceCreateMigrationBody{}

// MigrationServiceCreateMigrationBody struct for MigrationServiceCreateMigrationBody
type MigrationServiceCreateMigrationBody struct {
	// The display name of the migration.
	DisplayName string `json:"displayName"`
	// The data sources to migrate from.
	Sources []Source `json:"sources"`
	// The target database credentials.
	Target Target `json:"target"`
	// The migration mode (full+incremental or incremental-only).
	Mode TaskMode `json:"mode"`
	// Global binlog filter rule applied to all migrated tables.
	BinlogFilterRule     *BinlogFilterRule `json:"binlogFilterRule,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _MigrationServiceCreateMigrationBody MigrationServiceCreateMigrationBody

// NewMigrationServiceCreateMigrationBody instantiates a new MigrationServiceCreateMigrationBody object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMigrationServiceCreateMigrationBody(displayName string, sources []Source, target Target, mode TaskMode) *MigrationServiceCreateMigrationBody {
	this := MigrationServiceCreateMigrationBody{}
	this.DisplayName = displayName
	this.Sources = sources
	this.Target = target
	this.Mode = mode
	return &this
}

// NewMigrationServiceCreateMigrationBodyWithDefaults instantiates a new MigrationServiceCreateMigrationBody object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMigrationServiceCreateMigrationBodyWithDefaults() *MigrationServiceCreateMigrationBody {
	this := MigrationServiceCreateMigrationBody{}
	return &this
}

// GetDisplayName returns the DisplayName field value
func (o *MigrationServiceCreateMigrationBody) GetDisplayName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.DisplayName
}

// GetDisplayNameOk returns a tuple with the DisplayName field value
// and a boolean to check if the value has been set.
func (o *MigrationServiceCreateMigrationBody) GetDisplayNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DisplayName, true
}

// SetDisplayName sets field value
func (o *MigrationServiceCreateMigrationBody) SetDisplayName(v string) {
	o.DisplayName = v
}

// GetSources returns the Sources field value
func (o *MigrationServiceCreateMigrationBody) GetSources() []Source {
	if o == nil {
		var ret []Source
		return ret
	}

	return o.Sources
}

// GetSourcesOk returns a tuple with the Sources field value
// and a boolean to check if the value has been set.
func (o *MigrationServiceCreateMigrationBody) GetSourcesOk() ([]Source, bool) {
	if o == nil {
		return nil, false
	}
	return o.Sources, true
}

// SetSources sets field value
func (o *MigrationServiceCreateMigrationBody) SetSources(v []Source) {
	o.Sources = v
}

// GetTarget returns the Target field value
func (o *MigrationServiceCreateMigrationBody) GetTarget() Target {
	if o == nil {
		var ret Target
		return ret
	}

	return o.Target
}

// GetTargetOk returns a tuple with the Target field value
// and a boolean to check if the value has been set.
func (o *MigrationServiceCreateMigrationBody) GetTargetOk() (*Target, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Target, true
}

// SetTarget sets field value
func (o *MigrationServiceCreateMigrationBody) SetTarget(v Target) {
	o.Target = v
}

// GetMode returns the Mode field value
func (o *MigrationServiceCreateMigrationBody) GetMode() TaskMode {
	if o == nil {
		var ret TaskMode
		return ret
	}

	return o.Mode
}

// GetModeOk returns a tuple with the Mode field value
// and a boolean to check if the value has been set.
func (o *MigrationServiceCreateMigrationBody) GetModeOk() (*TaskMode, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Mode, true
}

// SetMode sets field value
func (o *MigrationServiceCreateMigrationBody) SetMode(v TaskMode) {
	o.Mode = v
}

// GetBinlogFilterRule returns the BinlogFilterRule field value if set, zero value otherwise.
func (o *MigrationServiceCreateMigrationBody) GetBinlogFilterRule() BinlogFilterRule {
	if o == nil || IsNil(o.BinlogFilterRule) {
		var ret BinlogFilterRule
		return ret
	}
	return *o.BinlogFilterRule
}

// GetBinlogFilterRuleOk returns a tuple with the BinlogFilterRule field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MigrationServiceCreateMigrationBody) GetBinlogFilterRuleOk() (*BinlogFilterRule, bool) {
	if o == nil || IsNil(o.BinlogFilterRule) {
		return nil, false
	}
	return o.BinlogFilterRule, true
}

// HasBinlogFilterRule returns a boolean if a field has been set.
func (o *MigrationServiceCreateMigrationBody) HasBinlogFilterRule() bool {
	if o != nil && !IsNil(o.BinlogFilterRule) {
		return true
	}

	return false
}

// SetBinlogFilterRule gets a reference to the given BinlogFilterRule and assigns it to the BinlogFilterRule field.
func (o *MigrationServiceCreateMigrationBody) SetBinlogFilterRule(v BinlogFilterRule) {
	o.BinlogFilterRule = &v
}

func (o MigrationServiceCreateMigrationBody) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MigrationServiceCreateMigrationBody) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["displayName"] = o.DisplayName
	toSerialize["sources"] = o.Sources
	toSerialize["target"] = o.Target
	toSerialize["mode"] = o.Mode
	if !IsNil(o.BinlogFilterRule) {
		toSerialize["binlogFilterRule"] = o.BinlogFilterRule
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *MigrationServiceCreateMigrationBody) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"displayName",
		"sources",
		"target",
		"mode",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varMigrationServiceCreateMigrationBody := _MigrationServiceCreateMigrationBody{}

	err = json.Unmarshal(data, &varMigrationServiceCreateMigrationBody)

	if err != nil {
		return err
	}

	*o = MigrationServiceCreateMigrationBody(varMigrationServiceCreateMigrationBody)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "displayName")
		delete(additionalProperties, "sources")
		delete(additionalProperties, "target")
		delete(additionalProperties, "mode")
		delete(additionalProperties, "binlogFilterRule")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableMigrationServiceCreateMigrationBody struct {
	value *MigrationServiceCreateMigrationBody
	isSet bool
}

func (v NullableMigrationServiceCreateMigrationBody) Get() *MigrationServiceCreateMigrationBody {
	return v.value
}

func (v *NullableMigrationServiceCreateMigrationBody) Set(val *MigrationServiceCreateMigrationBody) {
	v.value = val
	v.isSet = true
}

func (v NullableMigrationServiceCreateMigrationBody) IsSet() bool {
	return v.isSet
}

func (v *NullableMigrationServiceCreateMigrationBody) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMigrationServiceCreateMigrationBody(val *MigrationServiceCreateMigrationBody) *NullableMigrationServiceCreateMigrationBody {
	return &NullableMigrationServiceCreateMigrationBody{value: val, isSet: true}
}

func (v NullableMigrationServiceCreateMigrationBody) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMigrationServiceCreateMigrationBody) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
