/*
TiDB Cloud Starter and Essential API

TiDB Cloud Starter and Essential API

API version: v1beta1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package migration

import (
	"encoding/json"
)

// checks if the BinlogFilterRule type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BinlogFilterRule{}

// BinlogFilterRule Binlog filter rules applied during incremental replication.
type BinlogFilterRule struct {
	// Event types to ignore (e.g., \"truncate table\", \"drop database\").
	IgnoreEvent []string `json:"ignoreEvent,omitempty"`
	// SQL patterns to ignore.
	IgnoreSql            []string `json:"ignoreSql,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _BinlogFilterRule BinlogFilterRule

// NewBinlogFilterRule instantiates a new BinlogFilterRule object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBinlogFilterRule() *BinlogFilterRule {
	this := BinlogFilterRule{}
	return &this
}

// NewBinlogFilterRuleWithDefaults instantiates a new BinlogFilterRule object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBinlogFilterRuleWithDefaults() *BinlogFilterRule {
	this := BinlogFilterRule{}
	return &this
}

// GetIgnoreEvent returns the IgnoreEvent field value if set, zero value otherwise.
func (o *BinlogFilterRule) GetIgnoreEvent() []string {
	if o == nil || IsNil(o.IgnoreEvent) {
		var ret []string
		return ret
	}
	return o.IgnoreEvent
}

// GetIgnoreEventOk returns a tuple with the IgnoreEvent field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BinlogFilterRule) GetIgnoreEventOk() ([]string, bool) {
	if o == nil || IsNil(o.IgnoreEvent) {
		return nil, false
	}
	return o.IgnoreEvent, true
}

// HasIgnoreEvent returns a boolean if a field has been set.
func (o *BinlogFilterRule) HasIgnoreEvent() bool {
	if o != nil && !IsNil(o.IgnoreEvent) {
		return true
	}

	return false
}

// SetIgnoreEvent gets a reference to the given []string and assigns it to the IgnoreEvent field.
func (o *BinlogFilterRule) SetIgnoreEvent(v []string) {
	o.IgnoreEvent = v
}

// GetIgnoreSql returns the IgnoreSql field value if set, zero value otherwise.
func (o *BinlogFilterRule) GetIgnoreSql() []string {
	if o == nil || IsNil(o.IgnoreSql) {
		var ret []string
		return ret
	}
	return o.IgnoreSql
}

// GetIgnoreSqlOk returns a tuple with the IgnoreSql field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BinlogFilterRule) GetIgnoreSqlOk() ([]string, bool) {
	if o == nil || IsNil(o.IgnoreSql) {
		return nil, false
	}
	return o.IgnoreSql, true
}

// HasIgnoreSql returns a boolean if a field has been set.
func (o *BinlogFilterRule) HasIgnoreSql() bool {
	if o != nil && !IsNil(o.IgnoreSql) {
		return true
	}

	return false
}

// SetIgnoreSql gets a reference to the given []string and assigns it to the IgnoreSql field.
func (o *BinlogFilterRule) SetIgnoreSql(v []string) {
	o.IgnoreSql = v
}

func (o BinlogFilterRule) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BinlogFilterRule) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.IgnoreEvent) {
		toSerialize["ignoreEvent"] = o.IgnoreEvent
	}
	if !IsNil(o.IgnoreSql) {
		toSerialize["ignoreSql"] = o.IgnoreSql
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *BinlogFilterRule) UnmarshalJSON(data []byte) (err error) {
	varBinlogFilterRule := _BinlogFilterRule{}

	err = json.Unmarshal(data, &varBinlogFilterRule)

	if err != nil {
		return err
	}

	*o = BinlogFilterRule(varBinlogFilterRule)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "ignoreEvent")
		delete(additionalProperties, "ignoreSql")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableBinlogFilterRule struct {
	value *BinlogFilterRule
	isSet bool
}

func (v NullableBinlogFilterRule) Get() *BinlogFilterRule {
	return v.value
}

func (v *NullableBinlogFilterRule) Set(val *BinlogFilterRule) {
	v.value = val
	v.isSet = true
}

func (v NullableBinlogFilterRule) IsSet() bool {
	return v.isSet
}

func (v *NullableBinlogFilterRule) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBinlogFilterRule(val *BinlogFilterRule) *NullableBinlogFilterRule {
	return &NullableBinlogFilterRule{value: val, isSet: true}
}

func (v NullableBinlogFilterRule) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBinlogFilterRule) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
