/*
TiDB Cloud Starter and Essential API

TiDB Cloud Starter and Essential API

API version: v1beta1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package migration

import (
	"encoding/json"
)

// checks if the BlockAllowRules type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BlockAllowRules{}

// BlockAllowRules struct for BlockAllowRules
type BlockAllowRules struct {
	// Database names to include in migration.
	DoDbs []string `json:"doDbs,omitempty"`
	// Table-level allow-list rules.
	DoTables             []Table `json:"doTables,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _BlockAllowRules BlockAllowRules

// NewBlockAllowRules instantiates a new BlockAllowRules object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBlockAllowRules() *BlockAllowRules {
	this := BlockAllowRules{}
	return &this
}

// NewBlockAllowRulesWithDefaults instantiates a new BlockAllowRules object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBlockAllowRulesWithDefaults() *BlockAllowRules {
	this := BlockAllowRules{}
	return &this
}

// GetDoDbs returns the DoDbs field value if set, zero value otherwise.
func (o *BlockAllowRules) GetDoDbs() []string {
	if o == nil || IsNil(o.DoDbs) {
		var ret []string
		return ret
	}
	return o.DoDbs
}

// GetDoDbsOk returns a tuple with the DoDbs field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BlockAllowRules) GetDoDbsOk() ([]string, bool) {
	if o == nil || IsNil(o.DoDbs) {
		return nil, false
	}
	return o.DoDbs, true
}

// HasDoDbs returns a boolean if a field has been set.
func (o *BlockAllowRules) HasDoDbs() bool {
	if o != nil && !IsNil(o.DoDbs) {
		return true
	}

	return false
}

// SetDoDbs gets a reference to the given []string and assigns it to the DoDbs field.
func (o *BlockAllowRules) SetDoDbs(v []string) {
	o.DoDbs = v
}

// GetDoTables returns the DoTables field value if set, zero value otherwise.
func (o *BlockAllowRules) GetDoTables() []Table {
	if o == nil || IsNil(o.DoTables) {
		var ret []Table
		return ret
	}
	return o.DoTables
}

// GetDoTablesOk returns a tuple with the DoTables field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BlockAllowRules) GetDoTablesOk() ([]Table, bool) {
	if o == nil || IsNil(o.DoTables) {
		return nil, false
	}
	return o.DoTables, true
}

// HasDoTables returns a boolean if a field has been set.
func (o *BlockAllowRules) HasDoTables() bool {
	if o != nil && !IsNil(o.DoTables) {
		return true
	}

	return false
}

// SetDoTables gets a reference to the given []Table and assigns it to the DoTables field.
func (o *BlockAllowRules) SetDoTables(v []Table) {
	o.DoTables = v
}

func (o BlockAllowRules) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BlockAllowRules) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.DoDbs) {
		toSerialize["doDbs"] = o.DoDbs
	}
	if !IsNil(o.DoTables) {
		toSerialize["doTables"] = o.DoTables
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *BlockAllowRules) UnmarshalJSON(data []byte) (err error) {
	varBlockAllowRules := _BlockAllowRules{}

	err = json.Unmarshal(data, &varBlockAllowRules)

	if err != nil {
		return err
	}

	*o = BlockAllowRules(varBlockAllowRules)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "doDbs")
		delete(additionalProperties, "doTables")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableBlockAllowRules struct {
	value *BlockAllowRules
	isSet bool
}

func (v NullableBlockAllowRules) Get() *BlockAllowRules {
	return v.value
}

func (v *NullableBlockAllowRules) Set(val *BlockAllowRules) {
	v.value = val
	v.isSet = true
}

func (v NullableBlockAllowRules) IsSet() bool {
	return v.isSet
}

func (v *NullableBlockAllowRules) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBlockAllowRules(val *BlockAllowRules) *NullableBlockAllowRules {
	return &NullableBlockAllowRules{value: val, isSet: true}
}

func (v NullableBlockAllowRules) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBlockAllowRules) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
