/*
TiDB Cloud Starter and Essential API

TiDB Cloud Starter and Essential API

API version: v1beta1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package migration

import (
	"encoding/json"
)

// checks if the MigrationRule type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MigrationRule{}

// MigrationRule struct for MigrationRule
type MigrationRule struct {
	// Source table pattern to match.
	SourceTable *MigrationRuleSource `json:"sourceTable,omitempty"`
	// Target table to migrate to.
	TargetTable          *MigrationRuleTable `json:"targetTable,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _MigrationRule MigrationRule

// NewMigrationRule instantiates a new MigrationRule object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMigrationRule() *MigrationRule {
	this := MigrationRule{}
	return &this
}

// NewMigrationRuleWithDefaults instantiates a new MigrationRule object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMigrationRuleWithDefaults() *MigrationRule {
	this := MigrationRule{}
	return &this
}

// GetSourceTable returns the SourceTable field value if set, zero value otherwise.
func (o *MigrationRule) GetSourceTable() MigrationRuleSource {
	if o == nil || IsNil(o.SourceTable) {
		var ret MigrationRuleSource
		return ret
	}
	return *o.SourceTable
}

// GetSourceTableOk returns a tuple with the SourceTable field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MigrationRule) GetSourceTableOk() (*MigrationRuleSource, bool) {
	if o == nil || IsNil(o.SourceTable) {
		return nil, false
	}
	return o.SourceTable, true
}

// HasSourceTable returns a boolean if a field has been set.
func (o *MigrationRule) HasSourceTable() bool {
	if o != nil && !IsNil(o.SourceTable) {
		return true
	}

	return false
}

// SetSourceTable gets a reference to the given MigrationRuleSource and assigns it to the SourceTable field.
func (o *MigrationRule) SetSourceTable(v MigrationRuleSource) {
	o.SourceTable = &v
}

// GetTargetTable returns the TargetTable field value if set, zero value otherwise.
func (o *MigrationRule) GetTargetTable() MigrationRuleTable {
	if o == nil || IsNil(o.TargetTable) {
		var ret MigrationRuleTable
		return ret
	}
	return *o.TargetTable
}

// GetTargetTableOk returns a tuple with the TargetTable field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MigrationRule) GetTargetTableOk() (*MigrationRuleTable, bool) {
	if o == nil || IsNil(o.TargetTable) {
		return nil, false
	}
	return o.TargetTable, true
}

// HasTargetTable returns a boolean if a field has been set.
func (o *MigrationRule) HasTargetTable() bool {
	if o != nil && !IsNil(o.TargetTable) {
		return true
	}

	return false
}

// SetTargetTable gets a reference to the given MigrationRuleTable and assigns it to the TargetTable field.
func (o *MigrationRule) SetTargetTable(v MigrationRuleTable) {
	o.TargetTable = &v
}

func (o MigrationRule) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MigrationRule) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.SourceTable) {
		toSerialize["sourceTable"] = o.SourceTable
	}
	if !IsNil(o.TargetTable) {
		toSerialize["targetTable"] = o.TargetTable
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *MigrationRule) UnmarshalJSON(data []byte) (err error) {
	varMigrationRule := _MigrationRule{}

	err = json.Unmarshal(data, &varMigrationRule)

	if err != nil {
		return err
	}

	*o = MigrationRule(varMigrationRule)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "sourceTable")
		delete(additionalProperties, "targetTable")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableMigrationRule struct {
	value *MigrationRule
	isSet bool
}

func (v NullableMigrationRule) Get() *MigrationRule {
	return v.value
}

func (v *NullableMigrationRule) Set(val *MigrationRule) {
	v.value = val
	v.isSet = true
}

func (v NullableMigrationRule) IsSet() bool {
	return v.isSet
}

func (v *NullableMigrationRule) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMigrationRule(val *MigrationRule) *NullableMigrationRule {
	return &NullableMigrationRule{value: val, isSet: true}
}

func (v NullableMigrationRule) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMigrationRule) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
