// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// CompletePart complete part
//
// swagger:model CompletePart
type CompletePart struct {

	// The ETag of the part
	// Required: true
	Etag *string `json:"etag"`

	// The part number
	// Required: true
	PartNumber *int32 `json:"partNumber"`
}

// Validate validates this complete part
func (m *CompletePart) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateEtag(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validatePartNumber(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *CompletePart) validateEtag(formats strfmt.Registry) error {

	if err := validate.Required("etag", "body", m.Etag); err != nil {
		return err
	}

	return nil
}

func (m *CompletePart) validatePartNumber(formats strfmt.Registry) error {

	if err := validate.Required("partNumber", "body", m.PartNumber); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this complete part based on context it is used
func (m *CompletePart) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *CompletePart) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *CompletePart) UnmarshalBinary(b []byte) error {
	var res CompletePart
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
