// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// V1beta1CustomCSVFormat v1beta1 custom c s v format
//
// swagger:model v1beta1CustomCSVFormat
type V1beta1CustomCSVFormat struct {

	// backslash escape
	BackslashEscape bool `json:"backslashEscape,omitempty"`

	// delimiter
	Delimiter string `json:"delimiter,omitempty"`

	// header
	Header bool `json:"header,omitempty"`

	// not null
	NotNull bool `json:"notNull,omitempty"`

	// null
	Null string `json:"null,omitempty"`

	// separator
	Separator string `json:"separator,omitempty"`

	// trim last separator
	TrimLastSeparator bool `json:"trimLastSeparator,omitempty"`
}

// Validate validates this v1beta1 custom c s v format
func (m *V1beta1CustomCSVFormat) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this v1beta1 custom c s v format based on context it is used
func (m *V1beta1CustomCSVFormat) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *V1beta1CustomCSVFormat) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *V1beta1CustomCSVFormat) UnmarshalBinary(b []byte) error {
	var res V1beta1CustomCSVFormat
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
