// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/validate"
)

// V1beta1AuthType  - ACCESS_UNSPECIFIED: The access method is unknown.
//   - ROLE_ARN: The access method is role arn.
//   - ACCESS_KEY: The access method is access key.
//
// swagger:model v1beta1AuthType
type V1beta1AuthType string

func NewV1beta1AuthType(value V1beta1AuthType) *V1beta1AuthType {
	return &value
}

// Pointer returns a pointer to a freshly-allocated V1beta1AuthType.
func (m V1beta1AuthType) Pointer() *V1beta1AuthType {
	return &m
}

const (

	// V1beta1AuthTypeROLEARN captures enum value "ROLE_ARN"
	V1beta1AuthTypeROLEARN V1beta1AuthType = "ROLE_ARN"

	// V1beta1AuthTypeACCESSKEY captures enum value "ACCESS_KEY"
	V1beta1AuthTypeACCESSKEY V1beta1AuthType = "ACCESS_KEY"
)

// for schema
var v1beta1AuthTypeEnum []interface{}

func init() {
	var res []V1beta1AuthType
	if err := json.Unmarshal([]byte(`["ROLE_ARN","ACCESS_KEY"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		v1beta1AuthTypeEnum = append(v1beta1AuthTypeEnum, v)
	}
}

func (m V1beta1AuthType) validateV1beta1AuthTypeEnum(path, location string, value V1beta1AuthType) error {
	if err := validate.EnumCase(path, location, value, v1beta1AuthTypeEnum, true); err != nil {
		return err
	}
	return nil
}

// Validate validates this v1beta1 auth type
func (m V1beta1AuthType) Validate(formats strfmt.Registry) error {
	var res []error

	// value enum
	if err := m.validateV1beta1AuthTypeEnum("", "body", m); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// ContextValidate validates this v1beta1 auth type based on context it is used
func (m V1beta1AuthType) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}
