// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// V1beta1Import v1beta1 import
//
// swagger:model v1beta1Import
type V1beta1Import struct {

	// cluster Id
	// Read Only: true
	ClusterID string `json:"clusterId,omitempty"`

	// The process in percent of the import job, but doesn't include the post-processing progress.
	// Read Only: true
	CompletePercent int64 `json:"completePercent,omitempty"`

	// complete time
	// Read Only: true
	// Format: date-time
	CompleteTime *strfmt.DateTime `json:"completeTime,omitempty"`

	// create time
	// Read Only: true
	// Format: date-time
	CreateTime strfmt.DateTime `json:"createTime,omitempty"`

	// created by
	// Read Only: true
	CreatedBy string `json:"createdBy,omitempty"`

	// creation details
	// Read Only: true
	CreationDetails *V1beta1CreationDetails `json:"creationDetails,omitempty"`

	// id
	// Read Only: true
	ID string `json:"id,omitempty"`

	// message
	// Read Only: true
	Message string `json:"message,omitempty"`

	// name
	// Read Only: true
	Name string `json:"name,omitempty"`

	// state
	// Read Only: true
	State V1beta1ImportState `json:"state,omitempty"`

	// The total size of the data imported.
	// Read Only: true
	TotalSize string `json:"totalSize,omitempty"`
}

// Validate validates this v1beta1 import
func (m *V1beta1Import) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateCompleteTime(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateCreateTime(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateCreationDetails(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateState(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *V1beta1Import) validateCompleteTime(formats strfmt.Registry) error {
	if swag.IsZero(m.CompleteTime) { // not required
		return nil
	}

	if err := validate.FormatOf("completeTime", "body", "date-time", m.CompleteTime.String(), formats); err != nil {
		return err
	}

	return nil
}

func (m *V1beta1Import) validateCreateTime(formats strfmt.Registry) error {
	if swag.IsZero(m.CreateTime) { // not required
		return nil
	}

	if err := validate.FormatOf("createTime", "body", "date-time", m.CreateTime.String(), formats); err != nil {
		return err
	}

	return nil
}

func (m *V1beta1Import) validateCreationDetails(formats strfmt.Registry) error {
	if swag.IsZero(m.CreationDetails) { // not required
		return nil
	}

	if m.CreationDetails != nil {
		if err := m.CreationDetails.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("creationDetails")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("creationDetails")
			}
			return err
		}
	}

	return nil
}

func (m *V1beta1Import) validateState(formats strfmt.Registry) error {
	if swag.IsZero(m.State) { // not required
		return nil
	}

	if err := m.State.Validate(formats); err != nil {
		if ve, ok := err.(*errors.Validation); ok {
			return ve.ValidateName("state")
		} else if ce, ok := err.(*errors.CompositeError); ok {
			return ce.ValidateName("state")
		}
		return err
	}

	return nil
}

// ContextValidate validate this v1beta1 import based on the context it is used
func (m *V1beta1Import) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateClusterID(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateCompletePercent(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateCompleteTime(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateCreateTime(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateCreatedBy(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateCreationDetails(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateID(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateMessage(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateName(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateState(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateTotalSize(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *V1beta1Import) contextValidateClusterID(ctx context.Context, formats strfmt.Registry) error {

	if err := validate.ReadOnly(ctx, "clusterId", "body", string(m.ClusterID)); err != nil {
		return err
	}

	return nil
}

func (m *V1beta1Import) contextValidateCompletePercent(ctx context.Context, formats strfmt.Registry) error {

	if err := validate.ReadOnly(ctx, "completePercent", "body", int64(m.CompletePercent)); err != nil {
		return err
	}

	return nil
}

func (m *V1beta1Import) contextValidateCompleteTime(ctx context.Context, formats strfmt.Registry) error {

	if err := validate.ReadOnly(ctx, "completeTime", "body", m.CompleteTime); err != nil {
		return err
	}

	return nil
}

func (m *V1beta1Import) contextValidateCreateTime(ctx context.Context, formats strfmt.Registry) error {

	if err := validate.ReadOnly(ctx, "createTime", "body", strfmt.DateTime(m.CreateTime)); err != nil {
		return err
	}

	return nil
}

func (m *V1beta1Import) contextValidateCreatedBy(ctx context.Context, formats strfmt.Registry) error {

	if err := validate.ReadOnly(ctx, "createdBy", "body", string(m.CreatedBy)); err != nil {
		return err
	}

	return nil
}

func (m *V1beta1Import) contextValidateCreationDetails(ctx context.Context, formats strfmt.Registry) error {

	if m.CreationDetails != nil {

		if swag.IsZero(m.CreationDetails) { // not required
			return nil
		}

		if err := m.CreationDetails.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("creationDetails")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("creationDetails")
			}
			return err
		}
	}

	return nil
}

func (m *V1beta1Import) contextValidateID(ctx context.Context, formats strfmt.Registry) error {

	if err := validate.ReadOnly(ctx, "id", "body", string(m.ID)); err != nil {
		return err
	}

	return nil
}

func (m *V1beta1Import) contextValidateMessage(ctx context.Context, formats strfmt.Registry) error {

	if err := validate.ReadOnly(ctx, "message", "body", string(m.Message)); err != nil {
		return err
	}

	return nil
}

func (m *V1beta1Import) contextValidateName(ctx context.Context, formats strfmt.Registry) error {

	if err := validate.ReadOnly(ctx, "name", "body", string(m.Name)); err != nil {
		return err
	}

	return nil
}

func (m *V1beta1Import) contextValidateState(ctx context.Context, formats strfmt.Registry) error {

	if swag.IsZero(m.State) { // not required
		return nil
	}

	if err := m.State.ContextValidate(ctx, formats); err != nil {
		if ve, ok := err.(*errors.Validation); ok {
			return ve.ValidateName("state")
		} else if ce, ok := err.(*errors.CompositeError); ok {
			return ce.ValidateName("state")
		}
		return err
	}

	return nil
}

func (m *V1beta1Import) contextValidateTotalSize(ctx context.Context, formats strfmt.Registry) error {

	if err := validate.ReadOnly(ctx, "totalSize", "body", string(m.TotalSize)); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *V1beta1Import) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *V1beta1Import) UnmarshalBinary(b []byte) error {
	var res V1beta1Import
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
