/*
TiDB Cloud Dedicated Open API

TiDB Cloud Dedicated Open API.

API version: v1beta1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package dedicated

import (
	"encoding/json"
)

// checks if the V1beta1UpdateClusterRequestTidbNodeSetting type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &V1beta1UpdateClusterRequestTidbNodeSetting{}

// V1beta1UpdateClusterRequestTidbNodeSetting struct for V1beta1UpdateClusterRequestTidbNodeSetting
type V1beta1UpdateClusterRequestTidbNodeSetting struct {
	NodeSpecKey *string `json:"nodeSpecKey,omitempty"`
	TidbNodeGroups []UpdateClusterRequestTidbNodeSettingTidbNodeGroup `json:"tidbNodeGroups,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _V1beta1UpdateClusterRequestTidbNodeSetting V1beta1UpdateClusterRequestTidbNodeSetting

// NewV1beta1UpdateClusterRequestTidbNodeSetting instantiates a new V1beta1UpdateClusterRequestTidbNodeSetting object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV1beta1UpdateClusterRequestTidbNodeSetting() *V1beta1UpdateClusterRequestTidbNodeSetting {
	this := V1beta1UpdateClusterRequestTidbNodeSetting{}
	return &this
}

// NewV1beta1UpdateClusterRequestTidbNodeSettingWithDefaults instantiates a new V1beta1UpdateClusterRequestTidbNodeSetting object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV1beta1UpdateClusterRequestTidbNodeSettingWithDefaults() *V1beta1UpdateClusterRequestTidbNodeSetting {
	this := V1beta1UpdateClusterRequestTidbNodeSetting{}
	return &this
}

// GetNodeSpecKey returns the NodeSpecKey field value if set, zero value otherwise.
func (o *V1beta1UpdateClusterRequestTidbNodeSetting) GetNodeSpecKey() string {
	if o == nil || IsNil(o.NodeSpecKey) {
		var ret string
		return ret
	}
	return *o.NodeSpecKey
}

// GetNodeSpecKeyOk returns a tuple with the NodeSpecKey field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1beta1UpdateClusterRequestTidbNodeSetting) GetNodeSpecKeyOk() (*string, bool) {
	if o == nil || IsNil(o.NodeSpecKey) {
		return nil, false
	}
	return o.NodeSpecKey, true
}

// HasNodeSpecKey returns a boolean if a field has been set.
func (o *V1beta1UpdateClusterRequestTidbNodeSetting) HasNodeSpecKey() bool {
	if o != nil && !IsNil(o.NodeSpecKey) {
		return true
	}

	return false
}

// SetNodeSpecKey gets a reference to the given string and assigns it to the NodeSpecKey field.
func (o *V1beta1UpdateClusterRequestTidbNodeSetting) SetNodeSpecKey(v string) {
	o.NodeSpecKey = &v
}

// GetTidbNodeGroups returns the TidbNodeGroups field value if set, zero value otherwise.
func (o *V1beta1UpdateClusterRequestTidbNodeSetting) GetTidbNodeGroups() []UpdateClusterRequestTidbNodeSettingTidbNodeGroup {
	if o == nil || IsNil(o.TidbNodeGroups) {
		var ret []UpdateClusterRequestTidbNodeSettingTidbNodeGroup
		return ret
	}
	return o.TidbNodeGroups
}

// GetTidbNodeGroupsOk returns a tuple with the TidbNodeGroups field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1beta1UpdateClusterRequestTidbNodeSetting) GetTidbNodeGroupsOk() ([]UpdateClusterRequestTidbNodeSettingTidbNodeGroup, bool) {
	if o == nil || IsNil(o.TidbNodeGroups) {
		return nil, false
	}
	return o.TidbNodeGroups, true
}

// HasTidbNodeGroups returns a boolean if a field has been set.
func (o *V1beta1UpdateClusterRequestTidbNodeSetting) HasTidbNodeGroups() bool {
	if o != nil && !IsNil(o.TidbNodeGroups) {
		return true
	}

	return false
}

// SetTidbNodeGroups gets a reference to the given []UpdateClusterRequestTidbNodeSettingTidbNodeGroup and assigns it to the TidbNodeGroups field.
func (o *V1beta1UpdateClusterRequestTidbNodeSetting) SetTidbNodeGroups(v []UpdateClusterRequestTidbNodeSettingTidbNodeGroup) {
	o.TidbNodeGroups = v
}

func (o V1beta1UpdateClusterRequestTidbNodeSetting) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o V1beta1UpdateClusterRequestTidbNodeSetting) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.NodeSpecKey) {
		toSerialize["nodeSpecKey"] = o.NodeSpecKey
	}
	if !IsNil(o.TidbNodeGroups) {
		toSerialize["tidbNodeGroups"] = o.TidbNodeGroups
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *V1beta1UpdateClusterRequestTidbNodeSetting) UnmarshalJSON(data []byte) (err error) {
	varV1beta1UpdateClusterRequestTidbNodeSetting := _V1beta1UpdateClusterRequestTidbNodeSetting{}

	err = json.Unmarshal(data, &varV1beta1UpdateClusterRequestTidbNodeSetting)

	if err != nil {
		return err
	}

	*o = V1beta1UpdateClusterRequestTidbNodeSetting(varV1beta1UpdateClusterRequestTidbNodeSetting)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "nodeSpecKey")
		delete(additionalProperties, "tidbNodeGroups")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableV1beta1UpdateClusterRequestTidbNodeSetting struct {
	value *V1beta1UpdateClusterRequestTidbNodeSetting
	isSet bool
}

func (v NullableV1beta1UpdateClusterRequestTidbNodeSetting) Get() *V1beta1UpdateClusterRequestTidbNodeSetting {
	return v.value
}

func (v *NullableV1beta1UpdateClusterRequestTidbNodeSetting) Set(val *V1beta1UpdateClusterRequestTidbNodeSetting) {
	v.value = val
	v.isSet = true
}

func (v NullableV1beta1UpdateClusterRequestTidbNodeSetting) IsSet() bool {
	return v.isSet
}

func (v *NullableV1beta1UpdateClusterRequestTidbNodeSetting) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV1beta1UpdateClusterRequestTidbNodeSetting(val *V1beta1UpdateClusterRequestTidbNodeSetting) *NullableV1beta1UpdateClusterRequestTidbNodeSetting {
	return &NullableV1beta1UpdateClusterRequestTidbNodeSetting{value: val, isSet: true}
}

func (v NullableV1beta1UpdateClusterRequestTidbNodeSetting) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV1beta1UpdateClusterRequestTidbNodeSetting) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


