// Copyright 2025 PingCAP, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package flag

const (
	ClusterID            string = "cluster-id"
	ClusterIDShort       string = "c"
	LocalConcurrency     string = "local.concurrency"
	CSVBackslashEscape   string = "csv.backslash-escape"
	CSVDelimiter         string = "csv.delimiter"
	CSVSeparator         string = "csv.separator"
	CSVTrimLastSeparator string = "csv.trim-last-separator"
	CSVNullValue         string = "csv.null-value"
	CSVSkipHeader        string = "csv.skip-header"
	CSVNotNull           string = "csv.not-null"
	DisplayName          string = "display-name"
	DisplayNameShort     string = "n"
	BranchID             string = "branch-id"
	BranchIDShort        string = "b"
	Debug                string = "debug"
	DebugShort           string = "D"
	LocalFilePath        string = "local.file-path"
	Force                string = "force"
	ImportID             string = "import-id"
	NoColor              string = "no-color"
	Output               string = "output"
	OutputShort          string = "o"
	Password             string = "password"
	ProjectID            string = "project-id"
	ProjectIDShort       string = "p"
	ProfileName          string = "profile-name"
	Profile              string = "profile"
	ProfileShort         string = "P"
	PublicKey            string = "public-key"
	PrivateKey           string = "private-key"
	Query                string = "query"
	QueryShort           string = "q"
	Region               string = "region"
	RegionShort          string = "r"
	LocalTargetDatabase  string = "local.target-database"
	LocalTargetTable     string = "local.target-table"
	User                 string = "user"
	UserShort            string = "u"
	SpendingLimitMonthly string = "spending-limit-monthly"
	ServerlessLabels     string = "labels"
	Monthly              string = "monthly"
	BackupID             string = "backup-id"
	BackupTime           string = "backup-time"
	MinRCU               string = "min-rcu"
	MaxRCU               string = "max-rcu"
	StartIPAddress       string = "start-ip-address"
	EndIPAddress         string = "end-ip-address"
	NewStartIPAddress    string = "new-start-ip-address"
	NewEndIPAddress      string = "new-end-ip-address"
	NewDisplayName       string = "new-display-name"
	// External storage
	S3URI                  string = "s3.uri"
	S3AccessKeyID          string = "s3.access-key-id"
	S3SecretAccessKey      string = "s3.secret-access-key"
	S3RoleArn              string = "s3.role-arn"
	GCSURI                 string = "gcs.uri"
	GCSServiceAccountKey   string = "gcs.service-account-key"
	AzureBlobURI           string = "azblob.uri"
	AzureBlobSASToken      string = "azblob.sas-token"
	OSSURI                 string = "oss.uri"
	OSSAccessKeyID         string = "oss.access-key-id"
	OSSAccessKeySecret     string = "oss.access-key-secret"
	TargetType             string = "target-type"
	FileType               string = "file-type"
	ExportID               string = "export-id"
	ExportIDShort          string = "e"
	OutputPath             string = "output-path"
	Encryption             string = "encryption"
	Compression            string = "compression"
	SourceType             string = "source-type"
	UserRole               string = "role"
	AddRole                string = "add-role"
	DeleteRole             string = "delete-role"
	Concurrency            string = "concurrency"
	SQL                    string = "sql"
	TableWhere             string = "where"
	TableFilter            string = "filter"
	ParentID               string = "parent-id"
	ParentTimestamp        string = "parent-timestamp"
	PublicEndpointDisabled string = "disable-public-endpoint"
	ParquetCompression     string = "parquet.compression"
	StartDate              string = "start-date"
	EndDate                string = "end-date"
	Partitions             string = "partitions"

	AuditLogUnRedacted      string = "unredacted"
	AuditLogFilterRuleID    string = "filter-rule-id"
	AuditLogFilterRule      string = "rule"
	Enabled                 string = "enabled"
	CloudStorageType        string = "cloud-storage"
	RotationIntervalMinutes string = "rotation-interval-minutes"
	RotationSizeMib         string = "rotation-size-mib"

	ChangefeedType         string = "type"
	ChangefeedKafka        string = "kafka"
	ChangefeedMySQL        string = "mysql"
	ChangefeedFilter       string = "filter"
	ChangefeedStartTSO     string = "start-tso"
	ChangefeedStartTime    string = "start-time"
	ChangefeedID           string = "changefeed-id"
	ChangefeedIDShort      string = "f"
	Explain                string = "explain"
	ChangefeedTemplateType string = "type"
)

const OutputHelp = "Output format, one of [\"human\" \"json\"]. For the complete result, please use json format."
