name: Update manifest
on:
  workflow_dispatch:
  pull_request:
jobs:
  create-pr:
    uses: actions/versions-package-tools/.github/workflows/create-pr-to-update-manifest.yml@main
    with:
      tool-name: "ticloud"
    secrets: inherit
