name: Update latest version
on:
  workflow_dispatch:
  push:
    tags:
      - "v*"

jobs:
  create-pr:
     runs-on: ubuntu-latest
     steps:
        - name: Checkout code
          uses: actions/checkout@v3

        - name: Set up Go
          uses: actions/setup-go@v3
          with:
            go-version: 1.19

        - name: generate manifest
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          run: | 
            go run cmd/manifest/update_latest_version.go 

        - name: Create Pull Request
          uses: peter-evans/create-pull-request@v3
          with:
            token: ${{ secrets.GITHUB_TOKEN }}
            base: main
            commit-message: "update latest version"
            title: "update latest version"
            body: "Update latest-version file and version in install.sh"
            branch: "update-latest-version"

